/*
 * Copyright (c) 2018 ZENPE, Inc., and contributors.
 *
 * The MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <GYB/chain/get_config.hpp>
#include <GYB/chain/config.hpp>
#include <GYB/chain/protocol/types.hpp>

namespace GYB { namespace chain {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

   result[ "GYB_SYMBOL" ] = GYB_SYMBOL;
   result[ "GYB_ADDRESS_PREFIX" ] = GYB_ADDRESS_PREFIX;
   result[ "GYB_MIN_ACCOUNT_NAME_LENGTH" ] = GYB_MIN_ACCOUNT_NAME_LENGTH;
   result[ "GYB_MAX_ACCOUNT_NAME_LENGTH" ] = GYB_MAX_ACCOUNT_NAME_LENGTH;
   result[ "GYB_MIN_ASSET_SYMBOL_LENGTH" ] = GYB_MIN_ASSET_SYMBOL_LENGTH;
   result[ "GYB_MAX_ASSET_SYMBOL_LENGTH" ] = GYB_MAX_ASSET_SYMBOL_LENGTH;
   result[ "GYB_MAX_SHARE_SUPPLY" ] = GYB_MAX_SHARE_SUPPLY;
   result[ "GYB_MAX_PAY_RATE" ] = GYB_MAX_PAY_RATE;
   result[ "GYB_MAX_SIG_CHECK_DEPTH" ] = GYB_MAX_SIG_CHECK_DEPTH;
   result[ "GYB_MIN_TRANSACTION_SIZE_LIMIT" ] = GYB_MIN_TRANSACTION_SIZE_LIMIT;
   result[ "GYB_MIN_BLOCK_INTERVAL" ] = GYB_MIN_BLOCK_INTERVAL;
   result[ "GYB_MAX_BLOCK_INTERVAL" ] = GYB_MAX_BLOCK_INTERVAL;
   result[ "GYB_DEFAULT_BLOCK_INTERVAL" ] = GYB_DEFAULT_BLOCK_INTERVAL;
   result[ "GYB_DEFAULT_MAX_TRANSACTION_SIZE" ] = GYB_DEFAULT_MAX_TRANSACTION_SIZE;
   result[ "GYB_DEFAULT_MAX_BLOCK_SIZE" ] = GYB_DEFAULT_MAX_BLOCK_SIZE;
   result[ "GYB_DEFAULT_MAX_TIME_UNTIL_EXPIRATION" ] = GYB_DEFAULT_MAX_TIME_UNTIL_EXPIRATION;
   result[ "GYB_DEFAULT_MAINTENANCE_INTERVAL" ] = GYB_DEFAULT_MAINTENANCE_INTERVAL;
   result[ "GYB_DEFAULT_MAINTENANCE_SKIP_SLOTS" ] = GYB_DEFAULT_MAINTENANCE_SKIP_SLOTS;
   result[ "GYB_MIN_UNDO_HISTORY" ] = GYB_MIN_UNDO_HISTORY;
   result[ "GYB_MAX_UNDO_HISTORY" ] = GYB_MAX_UNDO_HISTORY;
   result[ "GYB_MIN_BLOCK_SIZE_LIMIT" ] = GYB_MIN_BLOCK_SIZE_LIMIT;
   result[ "GYB_MIN_TRANSACTION_EXPIRATION_LIMIT" ] = GYB_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result[ "GYB_BLOCKCHAIN_PRECISION" ] = GYB_BLOCKCHAIN_PRECISION;
   result[ "GYB_BLOCKCHAIN_PRECISION_DIGITS" ] = GYB_BLOCKCHAIN_PRECISION_DIGITS;
   result[ "GYB_DEFAULT_TRANSFER_FEE" ] = GYB_DEFAULT_TRANSFER_FEE;
   result[ "GYB_MAX_INSTANCE_ID" ] = GYB_MAX_INSTANCE_ID;
   result[ "GYB_100_PERCENT" ] = GYB_100_PERCENT;
   result[ "GYB_1_PERCENT" ] = GYB_1_PERCENT;
   result[ "GYB_MAX_MARKET_FEE_PERCENT" ] = GYB_MAX_MARKET_FEE_PERCENT;
   result[ "GYB_DEFAULT_FORCE_SETTLEMENT_DELAY" ] = GYB_DEFAULT_FORCE_SETTLEMENT_DELAY;
   result[ "GYB_DEFAULT_FORCE_SETTLEMENT_OFFSET" ] = GYB_DEFAULT_FORCE_SETTLEMENT_OFFSET;
   result[ "GYB_DEFAULT_FORCE_SETTLEMENT_MAX_VOLUME" ] = GYB_DEFAULT_FORCE_SETTLEMENT_MAX_VOLUME;
   result[ "GYB_DEFAULT_PRICE_FEED_LIFETIME" ] = GYB_DEFAULT_PRICE_FEED_LIFETIME;
   result[ "GYB_MAX_FEED_PRODUCERS" ] = GYB_MAX_FEED_PRODUCERS;
   result[ "GYB_DEFAULT_MAX_AUTHORITY_MEMBERSHIP" ] = GYB_DEFAULT_MAX_AUTHORITY_MEMBERSHIP;
   result[ "GYB_DEFAULT_MAX_ASSET_WHITELIST_AUTHORITIES" ] = GYB_DEFAULT_MAX_ASSET_WHITELIST_AUTHORITIES;
   result[ "GYB_DEFAULT_MAX_ASSET_FEED_PUBLISHERS" ] = GYB_DEFAULT_MAX_ASSET_FEED_PUBLISHERS;
   result[ "GYB_COLLATERAL_RATIO_DENOM" ] = GYB_COLLATERAL_RATIO_DENOM;
   result[ "GYB_MIN_COLLATERAL_RATIO" ] = GYB_MIN_COLLATERAL_RATIO;
   result[ "GYB_MAX_COLLATERAL_RATIO" ] = GYB_MAX_COLLATERAL_RATIO;
   result[ "GYB_DEFAULT_MAINTENANCE_COLLATERAL_RATIO" ] = GYB_DEFAULT_MAINTENANCE_COLLATERAL_RATIO;
   result[ "GYB_DEFAULT_MAX_SHORT_SQUEEZE_RATIO" ] = GYB_DEFAULT_MAX_SHORT_SQUEEZE_RATIO;
   result[ "GYB_DEFAULT_MARGIN_PERIOD_SEC" ] = GYB_DEFAULT_MARGIN_PERIOD_SEC;
   result[ "GYB_DEFAULT_MAX_WITNESSES" ] = GYB_DEFAULT_MAX_WITNESSES;
   result[ "GYB_DEFAULT_MAX_COMMITTEE" ] = GYB_DEFAULT_MAX_COMMITTEE;
   result[ "GYB_DEFAULT_MAX_PROPOSAL_LIFETIME_SEC" ] = GYB_DEFAULT_MAX_PROPOSAL_LIFETIME_SEC;
   result[ "GYB_DEFAULT_COMMITTEE_PROPOSAL_REVIEW_PERIOD_SEC" ] = GYB_DEFAULT_COMMITTEE_PROPOSAL_REVIEW_PERIOD_SEC;
   result[ "GYB_DEFAULT_NETWORK_PERCENT_OF_FEE" ] = GYB_DEFAULT_NETWORK_PERCENT_OF_FEE;
   result[ "GYB_DEFAULT_LIFETIME_REFERRER_PERCENT_OF_FEE" ] = GYB_DEFAULT_LIFETIME_REFERRER_PERCENT_OF_FEE;
   result[ "GYB_DEFAULT_MAX_BULK_DISCOUNT_PERCENT" ] = GYB_DEFAULT_MAX_BULK_DISCOUNT_PERCENT;
   result[ "GYB_DEFAULT_BULK_DISCOUNT_THRESHOLD_MIN" ] = GYB_DEFAULT_BULK_DISCOUNT_THRESHOLD_MIN;
   result[ "GYB_DEFAULT_BULK_DISCOUNT_THRESHOLD_MAX" ] = GYB_DEFAULT_BULK_DISCOUNT_THRESHOLD_MAX;
   result[ "GYB_DEFAULT_CASHBACK_VESTING_PERIOD_SEC" ] = GYB_DEFAULT_CASHBACK_VESTING_PERIOD_SEC;
   result[ "GYB_DEFAULT_CASHBACK_VESTING_THRESHOLD" ] = GYB_DEFAULT_CASHBACK_VESTING_THRESHOLD;
   result[ "GYB_DEFAULT_BURN_PERCENT_OF_FEE" ] = GYB_DEFAULT_BURN_PERCENT_OF_FEE;
   result[ "GYB_WITNESS_PAY_PERCENT_PRECISION" ] = GYB_WITNESS_PAY_PERCENT_PRECISION;
   result[ "GYB_DEFAULT_MAX_ASSERT_OPCODE" ] = GYB_DEFAULT_MAX_ASSERT_OPCODE;
   result[ "GYB_DEFAULT_FEE_LIQUIDATION_THRESHOLD" ] = GYB_DEFAULT_FEE_LIQUIDATION_THRESHOLD;
   result[ "GYB_DEFAULT_ACCOUNTS_PER_FEE_SCALE" ] = GYB_DEFAULT_ACCOUNTS_PER_FEE_SCALE;
   result[ "GYB_DEFAULT_ACCOUNT_FEE_SCALE_BITSHIFTS" ] = GYB_DEFAULT_ACCOUNT_FEE_SCALE_BITSHIFTS;
   result[ "GYB_MAX_WORKER_NAME_LENGTH" ] = GYB_MAX_WORKER_NAME_LENGTH;
   result[ "GYB_MAX_URL_LENGTH" ] = GYB_MAX_URL_LENGTH;
   result[ "GYB_NEAR_SCHEDULE_CTR_IV" ] = GYB_NEAR_SCHEDULE_CTR_IV;
   result[ "GYB_FAR_SCHEDULE_CTR_IV" ] = GYB_FAR_SCHEDULE_CTR_IV;
   result[ "GYB_CORE_ASSET_CYCLE_RATE" ] = GYB_CORE_ASSET_CYCLE_RATE;
   result[ "GYB_CORE_ASSET_CYCLE_RATE_BITS" ] = GYB_CORE_ASSET_CYCLE_RATE_BITS;
   result[ "GYB_DEFAULT_WITNESS_PAY_PER_BLOCK" ] = GYB_DEFAULT_WITNESS_PAY_PER_BLOCK;
   result[ "GYB_DEFAULT_WITNESS_PAY_VESTING_SECONDS" ] = GYB_DEFAULT_WITNESS_PAY_VESTING_SECONDS;
   result[ "GYB_DEFAULT_WORKER_BUDGET_PER_DAY" ] = GYB_DEFAULT_WORKER_BUDGET_PER_DAY;
   result[ "GYB_MAX_INTEREST_APR" ] = GYB_MAX_INTEREST_APR;
   result[ "GYB_COMMITTEE_ACCOUNT" ] = GYB_COMMITTEE_ACCOUNT;
   result[ "GYB_WITNESS_ACCOUNT" ] = GYB_WITNESS_ACCOUNT;
   result[ "GYB_RELAXED_COMMITTEE_ACCOUNT" ] = GYB_RELAXED_COMMITTEE_ACCOUNT;
   result[ "GYB_NULL_ACCOUNT" ] = GYB_NULL_ACCOUNT;
   result[ "GYB_TEMP_ACCOUNT" ] = GYB_TEMP_ACCOUNT;

   return result;
}

} } // GYB::chain
